# Site settings
title: Ethan Teague
name: Ethan Teague

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ethanteague
 - title: Drupal
   url: https://www.drupal.org/u/ethant
 - title: LinkedIn
   url: https://www.linkedin.com/in/ethan-teague-ab377421/

#Any buzzword skills you want to include
skills:
 - Drupal
 - Php
 - OOP
 - JS / Multiple JS Frameworks
 - Linux
 - Migrations
 - DevOps
 - Automated Testing
 - Automated Deployment

#Work experience is required
roles:
 - title: Senior Engineer
   start: 2013
   end: Ongoing
   employer: CivicActions
   url: https://civicactions.com/team/ethan-teague/
   description: Provide tech lead, architecture, and development services for agile develpment shop specializing in Drupal and Federal Government work
 - title: Engineer
   start: 2011
   end: 2013
   employer: MilesMedia
   url: http://www.milespartnership.com/
   description: Provided Drupal development services for agency shop specializing in Tourism website and software development
 - title: CTO
   start: 1997
   end: 2011
   employer: Palm Mortgage
   description: Provided tech support and software development services for Mortgage Lender

#Education is required
education:
 - level: Bachelor of Arts (B.A.)
   date: 1997
   subject: English Literature
   school: University of Tennessee

#List of interesting Github repo/projects to include - optional
github:
 - ethanteague/agile-ms
 - ethanteague/petitions
 - ethanteague/dkan_sci_metadata
 - ethanteague/dkan-bowline
 - ethanteague/nebula
 - ethanteague/redditview
 - ethanteague/govpress
 - ethanteague/give-it-away-now

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>General:</strong> 
  I have been a Drupal developer for 10 years, and I am comfortable with both server and client side development. I am a full stack, DevOps developer: Jenkins, Behat, server optimization and deployment processes are in my toolbelt. Drupal module development, theming, and optimization are also skills I possess. Experienced with Node frameworks and tools.
